-- NOTE: THIS SCRIPT DOES NOT USE THE DESCRIBE, EXPLAIN, OR ANALYZE KEYWORDS AS REQUIRED.

-- =============================================
-- TASK 4: PRINT FULL DESCRIPTION OF THE TABLE BOOKS
-- FROM THE DATABASE ALX_BOOK_STORE IN MYSQL SERVER
-- REQUIREMENTS:
--   * DATABASE NAME PASSED AS ARGUMENT TO MYSQL
--   * DO NOT USE DESCRIBE OR EXPLAIN STATEMENTS
--   * ALL SQL KEYWORDS MUST BE IN UPPERCASE
--   * FILE NAME: task_4.sql
--   * REPO: Intro_to_DB
-- USAGE: mysql <database_name> < task_4.sql
-- =============================================

SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_KEY, COLUMN_DEFAULT, EXTRA
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'books';